<?php
defined( 'ABSPATH' ) || exit;

function matin_parto_register_testimonials(){register_post_type('mp_testimonial',array('labels'=>array('name'=>'نظرات زبان‌آموزان','singular_name'=>'نظر زبان‌آموز','add_new'=>'افزودن نظر','add_new_item'=>'افزودن نظر زبان‌آموز','edit_item'=>'ویرایش نظر زبان‌آموز','new_item'=>'نظر جدید','view_item'=>'مشاهده نظر','search_items'=>'جستجوی نظرات','not_found'=>'نظری پیدا نشد','menu_name'=>'نظرات زبان‌آموزان'),'public'=>false,'show_ui'=>true,'show_in_menu'=>true,'show_in_admin_bar'=>true,'menu_position'=>26,'menu_icon'=>'dashicons-format-chat','supports'=>array('title','editor','thumbnail'),'show_in_rest'=>true,'has_archive'=>false,'capability_type'=>'post','map_meta_cap'=>true));}
add_action('init','matin_parto_register_testimonials');
function matin_parto_testimonial_meta_box(){add_meta_box('matin_parto_testimonial_details','اطلاعات نظر زبان‌آموز','matin_parto_testimonial_meta_box_html','mp_testimonial','side','high');}add_action('add_meta_boxes','matin_parto_testimonial_meta_box');
function matin_parto_testimonial_meta_box_html($post){wp_nonce_field('matin_parto_testimonial_details','matin_parto_testimonial_nonce');$rating=max(1,min(5,absint(get_post_meta($post->ID,'_mp_testimonial_rating',true)?:5)));$course=get_post_meta($post->ID,'_mp_testimonial_course',true);?><p><label for="mp_testimonial_rating"><strong>امتیاز (ستاره)</strong></label><select class="widefat" id="mp_testimonial_rating" name="mp_testimonial_rating"><?php for($i=5;$i>=1;$i--):?><option value="<?php echo esc_attr($i);?>" <?php selected($rating,$i);?>><?php echo esc_html($i.' ستاره');?></option><?php endfor;?></select></p><p><label for="mp_testimonial_course"><strong>نوع یادگیری / دوره</strong></label><input class="widefat" type="text" id="mp_testimonial_course" name="mp_testimonial_course" value="<?php echo esc_attr($course);?>" placeholder="مثلاً زبان‌آموز دوره مکالمه"></p><p class="description">عکس زبان‌آموز را از «تصویر شاخص» انتخاب کنید و متن نظر را در ویرایشگر بنویسید.</p><?php}
function matin_parto_save_testimonial_meta($post_id){if(!isset($_POST['matin_parto_testimonial_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['matin_parto_testimonial_nonce'])),'matin_parto_testimonial_details'))return;if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('edit_post',$post_id)||'mp_testimonial'!==get_post_type($post_id))return;$rating=max(1,min(5,absint($_POST['mp_testimonial_rating']??5)));$course=sanitize_text_field(wp_unslash($_POST['mp_testimonial_course']??''));update_post_meta($post_id,'_mp_testimonial_rating',$rating);update_post_meta($post_id,'_mp_testimonial_course',$course);}add_action('save_post_mp_testimonial','matin_parto_save_testimonial_meta');
function matin_parto_testimonial_admin_columns($columns){return array('cb'=>$columns['cb'],'title'=>'نام زبان‌آموز','course'=>'نوع دوره / یادگیری','rating'=>'امتیاز','thumbnail'=>'عکس','date'=>'تاریخ');}add_filter('manage_mp_testimonial_posts_columns','matin_parto_testimonial_admin_columns');
function matin_parto_testimonial_admin_column_content($column,$post_id){if('course'===$column)echo esc_html(get_post_meta($post_id,'_mp_testimonial_course',true));elseif('rating'===$column){$rating=max(1,min(5,absint(get_post_meta($post_id,'_mp_testimonial_rating',true)?:5)));echo esc_html(str_repeat('★',$rating));}elseif('thumbnail'===$column)echo has_post_thumbnail($post_id)?get_the_post_thumbnail($post_id,array(48,48),array('style'=>'width:48px;height:48px;object-fit:cover;border-radius:50%;')):'—';}add_action('manage_mp_testimonial_posts_custom_column','matin_parto_testimonial_admin_column_content',10,2);
function matin_parto_add_social_customizer($wp_customize){$wp_customize->add_section('matin_parto_social_links',array('title'=>'شبکه‌های اجتماعی','priority'=>150,'description'=>'لینک‌های شبکه‌های اجتماعی در بنر پایین صفحه اصلی.'));foreach(array('whatsapp'=>'واتساپ','telegram'=>'تلگرام','instagram'=>'اینستاگرام','youtube'=>'یوتیوب') as $key=>$label){$setting='matin_parto_social_'.$key;$wp_customize->add_setting($setting,array('default'=>'','sanitize_callback'=>'esc_url_raw','transport'=>'refresh'));$wp_customize->add_control($setting,array('label'=>'لینک '.$label,'section'=>'matin_parto_social_links','type'=>'url','description'=>'آدرس کامل لینک '.$label.' را وارد کنید.'));}}add_action('customize_register','matin_parto_add_social_customizer',20);
function matin_parto_social_icon($network){$icons=array('whatsapp'=>'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.7a8.3 8.3 0 0 1-12.2 7.1L4 20l1.3-4.1a8.3 8.3 0 1 1 15.2-4.2Z"/><path d="M9 8.4c.2-.4.4-.4.7-.4h.5c.2 0 .4.1.5.4l.7 1.7c.1.2.1.4-.1.6l-.5.6c.6 1.1 1.5 2 2.7 2.5l.5-.6c.2-.2.4-.2.6-.1l1.6.8c.3.1.4.3.3.6-.2.8-.9 1.4-1.8 1.4-3.2-.1-6.8-3.7-6.9-6.9 0-.2.1-.4.2-.6.1-.2.2-.3.3-.5Z"/></svg>','telegram'=>'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 4 3.8 10.6c-.7.3-.7 1.2.1 1.5l4.4 1.6 1.7 5.1c.2.6 1 .7 1.4.2l2.5-3.1 4.4 3.2c.5.4 1.2.1 1.4-.5L22 5c.1-.7-.4-1.2-1-1Z"/><path d="m8.4 13.7 8.8-6.1-6.2 7.5"/></svg>','instagram'=>'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="3.5" width="17" height="17" rx="4"/><circle cx="12" cy="12" r="4"/><circle cx="17.4" cy="6.8" r="1" fill="currentColor" stroke="none"/></svg>','youtube'=>'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 8.2a2.8 2.8 0 0 0-2-2C17.3 5.7 12 5.7 12 5.7s-5.3 0-7 .5a2.8 2.8 0 0 0-2 2A29 29 0 0 0 2.5 12 29 29 0 0 0 3 15.8a2.8 2.8 0 0 0 2 2c1.7.5 7 .5 7 .5s5.3 0 7-.5a2.8 2.8 0 0 0 2-2 29 29 0 0 0 .5-3.8 29 29 0 0 0-.5-3.8Z"/><path d="m10 9 5 3-5 3V9Z" fill="currentColor" stroke="none"/></svg>');return $icons[$network]??'';}
function matin_parto_social_links_html($class=''){$socials=array('whatsapp'=>'واتساپ','telegram'=>'تلگرام','instagram'=>'اینستاگرام','youtube'=>'یوتیوب');echo '<div class="mp-home-social-links '.esc_attr($class).'" aria-label="شبکه‌های اجتماعی">';foreach($socials as $key=>$label){$url=get_theme_mod('matin_parto_social_'.$key,'');echo '<a class="mp-home-social-link mp-home-social-link--'.esc_attr($key).'" href="'.esc_url($url?:'#').'"'.($url?' target="_blank" rel="noopener noreferrer"':' aria-disabled="true"').' aria-label="'.esc_attr($label).'">'.matin_parto_social_icon($key).'<span>'.esc_html($label).'</span></a>';}echo '</div>';}
function matin_parto_get_testimonials($limit=3){return new WP_Query(array('post_type'=>'mp_testimonial','post_status'=>'publish','posts_per_page'=>absint($limit),'orderby'=>'date','order'=>'DESC','no_found_rows'=>true));}
function matin_parto_ensure_about_page(){if(get_option('matin_parto_about_page_ready'))return;$page=get_page_by_path('about');if(!$page){$id=wp_insert_post(array('post_title'=>'درباره من','post_name'=>'about','post_status'=>'publish','post_type'=>'page','post_content'=>''),true);if(!is_wp_error($id))update_option('matin_parto_about_page_ready',1);}else update_option('matin_parto_about_page_ready',1);}add_action('init','matin_parto_ensure_about_page',20);
function matin_parto_about_customizer($wp_customize){$wp_customize->add_section('matin_parto_about_images',array('title'=>'صفحه «درباره من»','priority'=>145,'description'=>'تمام تصاویر بخش درباره من را از کتابخانه رسانه انتخاب کنید.'));$items=array('hero'=>array('عکس اصلی درباره من','تصویر اصلی بالای صفحه'),'video'=>array('عکس بخش مسیر من','تصویر سمت چپ بخش چطور وارد دنیای آموزش شدم'),'story'=>array('عکس داستان من','تصویر جایگزین بخش معرفی'),'extra'=>array('تصویر اضافی درباره من','تصویر عریض اختیاری قبل از نظر زبان‌آموز'));foreach($items as $key=>$item){$setting='matin_parto_about_'.$key.'_image';$wp_customize->add_setting($setting,array('default'=>'','sanitize_callback'=>'esc_url_raw','transport'=>'refresh'));$wp_customize->add_control(new WP_Customize_Image_Control($wp_customize,$setting,array('label'=>$item[0],'section'=>'matin_parto_about_images','description'=>$item[1])));}}add_action('customize_register','matin_parto_about_customizer',25);

function matin_parto_about_full_customizer($wp_customize){
    $section='matin_parto_about_content';
    $wp_customize->add_section($section,array('title'=>'درباره ما','priority'=>146,'description'=>'تمام متن‌ها، تصاویر، ویدیو، آمار، مزیت‌ها و نظر زبان‌آموز صفحه درباره من را از این بخش تغییر دهید.'));
    $fields=array(
        'hero_title'=>array('سلام، من متین پارتو هستم','عنوان اصلی','text'),
        'hero_subtitle'=>array('مدرس زبان انگلیسی','عنوان رنگی زیر عنوان','text'),
        'hero_text'=>array('من به آموزش زبان انگلیسی به‌عنوان یک ابزار قدرتمند برای ساختن آینده‌ی بهتر باور دارم. در این مسیر، هدف من فقط آموزش گرامر زبان نیست، بلکه همراهی با شما برای رسیدن به اهداف و رویاهایتان است.','متن معرفی','textarea'),
        'hero_signature'=>array('Matin Parto','امضای بخش اول','text'),
        'hero_button'=>array('تماس با من','متن دکمه','text'),
        'story_kicker'=>array('مسیر من','برچسب بخش مسیر من','text'),
        'story_title'=>array('چطور وارد دنیای آموزش شدم؟','عنوان مسیر من','text'),
        'story_text_1'=>array('همیشه به زبان و ارتباط با آدم‌های مختلف علاقه داشتم. زمانی که متوجه شدم آموزش زبان می‌تواند زندگی خیلی از افراد را تغییر دهد، تصمیم گرفتم این مسیر را جدی دنبال کنم.','متن اول مسیر من','textarea'),
        'story_text_2'=>array('بعد از سال‌ها تجربه‌ی یادگیری و تدریس، امروز با افتخار در کنار شما هستم تا بهترین تجربه‌ی یادگیری را رقم بزنیم.','متن دوم مسیر من','textarea'),
        'video_url'=>array('','لینک مستقیم ویدیو MP4','url'),
        'video_caption'=>array('Better\nEnglish\nBigger\nDreams','متن روی ویدیو','textarea'),
        'why_kicker'=>array('چرا من؟','برچسب بخش چرا من','text'),
        'why_title'=>array('آنچه یادگیری با من را متفاوت می‌کند','عنوان بخش چرا من','text'),
        'testimonial_name'=>array('سارا محمدی','نام زبان‌آموز','text'),
        'testimonial_course'=>array('دانشجوی دوره Intermediate','دوره / توضیح کوتاه','text'),
        'testimonial_text'=>array('متین پارتو فقط یک مدرس نیست، یک همراه واقعی در مسیر یادگیریه. با صبر، انگیزه و روش‌های عالی تدریسش باعث شد با اعتماد به نفس بیشتری صحبت کنم.','متن نظر زبان‌آموز','textarea'),
        'testimonial_rating'=>array('5','امتیاز نظر از ۱ تا ۵','number'),
    );
    foreach($fields as $key=>$data){$setting='matin_parto_about_'.$key;$sanitize=($data[2]==='url'?'esc_url_raw':($data[2]==='number'?'absint':($data[2]==='textarea'?'sanitize_textarea_field':'sanitize_text_field')));$wp_customize->add_setting($setting,array('default'=>$data[0],'sanitize_callback'=>$sanitize,'transport'=>'refresh'));$control=array('label'=>$data[1],'section'=>$section,'type'=>$data[2]);if($data[2]==='number'){$control['input_attrs']=array('min'=>1,'max'=>5);} $wp_customize->add_control($setting,$control);}
    foreach(array('hero_image'=>array('تصویر اصلی هیرو','عکس بزرگ بالای صفحه'),'story_image'=>array('تصویر مسیر من','عکس بخش مسیر من'),'video_image'=>array('تصویر پوستر ویدیو','پوستر ویدیو در صورت وجود'),'testimonial_image'=>array('عکس زبان‌آموز','عکس سارا محمدی در بخش نظر')) as $key=>$data){$setting='matin_parto_about_'.$key;$wp_customize->add_setting($setting,array('default'=>'','sanitize_callback'=>'esc_url_raw','transport'=>'refresh'));$wp_customize->add_control(new WP_Customize_Image_Control($wp_customize,$setting,array('label'=>$data[0],'section'=>$section,'description'=>$data[1])));}
    for($i=1;$i<=4;$i++){$setting='matin_parto_about_stat_'.$i;$wp_customize->add_setting($setting,array('default'=>array('1'=>'+۱۰ سال','2'=>'+۵۰۰','3'=>'۹۸٪','4'=>'۳ زبان')[$i],'sanitize_callback'=>'sanitize_text_field','transport'=>'refresh'));$wp_customize->add_control($setting,array('label'=>'آمار '.$i,'section'=>$section,'type'=>'text'));$setting2='matin_parto_about_stat_'.$i.'_label';$defaults=array('تجربه تدریس حرفه‌ای','دانشجوی موفق','رضایت دانشجویان','تسلط به زبان‌های انگلیسی، آلمانی و فرانسه');$wp_customize->add_setting($setting2,array('default'=>$defaults[$i-1],'sanitize_callback'=>'sanitize_text_field','transport'=>'refresh'));$wp_customize->add_control($setting2,array('label'=>'توضیح آمار '.$i,'section'=>$section,'type'=>'text'));}
    $reason_defaults=array(array('برنامه‌ریزی شخصی‌سازی‌شده','با توجه به سطح، هدف و سبک یادگیری شما برنامه اختصاصی طراحی می‌کنم.'),array('پشتیبانی همیشگی','در تمام مراحل یادگیری همراه شما هستم و به سوالاتتان پاسخ می‌دهم.'),array('تجربه و تخصص','سال‌ها تدریس و تجربه موفق در آزمون‌های بین‌المللی.'),array('روش تدریس مدرن و تعاملی','استفاده از تکنیک‌های به‌روز و تمرین‌های عملی برای یادگیری عمیق‌تر.'),array('نتایج ملموس','با تمرکز بر مکالمه، شنیداری و مهارت‌های کاربردی، پیشرفت شما را دنبال می‌کنم.'),array('تعهد و علاقه واقعی','من به آموزش و موفقیت شما اهمیت می‌دهم و با تمام توان در کنارتان هستم.'));
    for($i=1;$i<=6;$i++){foreach(array('title','text') as $part){$key='reason_'.$i.'_'.$part;$default=$reason_defaults[$i-1][$part==='title'?0:1];$wp_customize->add_setting('matin_parto_about_'.$key,array('default'=>$default,'sanitize_callback'=>$part==='text'?'sanitize_textarea_field':'sanitize_text_field','transport'=>'refresh'));$wp_customize->add_control('matin_parto_about_'.$key,array('label'=>'مورد '.$i.' — '.($part==='title'?'عنوان':'توضیح'),'section'=>$section,'type'=>$part==='text'?'textarea':'text'));}}
}
add_action('customize_register','matin_parto_about_full_customizer',26);

function matin_parto_about_assets(){if(is_page('about'))wp_enqueue_style('matin-parto-about',get_template_directory_uri().'/assets/css/about-page.css',array('matin-parto-cta-social'),'2026.09.15');}add_action('wp_enqueue_scripts','matin_parto_about_assets',30);
/* هر آیتم منو با عنوان «درباره من» یا «درباره» به همین صفحه هدایت می‌شود؛ حتی اگر منوی سفارشی وردپرس باشد. */
function matin_parto_force_about_menu_url($atts,$item,$args){$title=wp_strip_all_tags($item->title??'');if(preg_match('/درباره\s*(من|ما)?/u',$title))$atts['href']=home_url('/about/');return $atts;}add_filter('nav_menu_link_attributes','matin_parto_force_about_menu_url',10,3);
