<?php
defined( 'ABSPATH' ) || exit;

$contact = function( $key, $default = '' ) {
    return get_theme_mod( 'matin_parto_contact_' . $key, $default );
};
$home = function_exists( 'matin_parto_home_settings' ) ? matin_parto_home_settings() : array();
$hero_image = $contact( 'hero_image', '' );
if ( ! $hero_image && ! empty( $home['hero_image'] ) ) { $hero_image = $home['hero_image']; }
$aside_image = $contact( 'aside_image', '' );
$map_image = $contact( 'map_image', '' );
$sent = isset( $_GET['contact'] ) && 'sent' === sanitize_key( wp_unslash( $_GET['contact'] ) );
$error = isset( $_GET['contact'] ) && 'error' === sanitize_key( wp_unslash( $_GET['contact'] ) );

get_header();
?>
<link rel="stylesheet" id="matin-parto-contact-page-css" href="<?php echo esc_url( get_theme_file_uri( 'assets/css/contact-page.css' ) ); ?>?ver=20260915-1" media="all">
<main class="mp-contact-page" dir="rtl">
<section class="mp-contact-hero"><div class="mp-container mp-contact-hero__grid"><div class="mp-contact-hero__visual"><div class="mp-contact-hero__arch" aria-hidden="true"></div><?php if ( $hero_image ) : ?><img src="<?php echo esc_url( $hero_image ); ?>" alt="متین پارتو" loading="eager" fetchpriority="high"><?php else : ?><div class="mp-contact-image-placeholder">عکس مدرس</div><?php endif; ?><span class="mp-contact-handwrite" aria-hidden="true">Let's<br>Keep in<br>Touch</span></div><div class="mp-contact-hero__copy"><div class="mp-contact-kicker">تماس با ما <i></i></div><h1>با ما در ارتباط باشید</h1><h2>همیشه پاسخگوی سوالات شما هستیم</h2><p>اگر سوالی درباره دوره‌ها، نحوه ثبت‌نام، پشتیبانی و یا هر موضوع دیگری دارید، خوشحال می‌شویم از طریق یکی از راه‌های ارتباطی زیر با ما در تماس باشید. ما در سریع‌ترین زمان ممکن پاسخگوی شما خواهیم بود.</p><div class="mp-contact-signature">Matin Parto</div></div></div></section>

<section class="mp-contact-info mp-container" aria-label="اطلاعات تماس">
<article class="mp-contact-info-card"><span class="mp-contact-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M7.1 4.2 4.8 5.4c-.7.4-.9 1.2-.6 1.9 2.4 5.9 6.6 9.9 12.5 12.3.7.3 1.5 0 1.9-.6l1.2-2.3c.3-.6.1-1.3-.5-1.7l-3-1.7c-.5-.3-1.2-.2-1.6.3l-1.1 1.3c-2.4-1.3-4.2-3.1-5.5-5.5l1.3-1.1c.5-.4.6-1.1.3-1.6l-1.7-3c-.3-.6-1.1-.8-1.7-.5Z"/></svg></span><h3>شماره تماس</h3><p>شنبه تا پنجشنبه، ۹ صبح تا ۶ عصر</p><a href="tel:+989123456789">+98 912 345 6789</a></article>
<article class="mp-contact-info-card"><span class="mp-contact-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg></span><h3>ایمیل</h3><p>در هر زمان آماده پاسخگویی هستیم</p><a href="mailto:info@matinparto.com">info@matinparto.com</a></article>
<article class="mp-contact-info-card"><span class="mp-contact-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 21s7-6.3 7-12a7 7 0 1 0-14 0c0 5.7 7 12 7 12Z"/><circle cx="12" cy="9" r="2.2"/></svg></span><h3>آدرس</h3><p>تهران، خیابان ولیعصر، پلاک ۱۳۲</p><span>ساختمان متین پارتو، طبقه ۳</span></article>
<article class="mp-contact-info-card"><span class="mp-contact-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M7 17.5a3.5 3.5 0 0 1 0-7h2"/><path d="M15 6.5a3.5 3.5 0 0 1 0 7h-2"/><path d="m8 14 8-4"/></svg></span><h3>شبکه‌های اجتماعی</h3><p>ما را در شبکه‌های اجتماعی دنبال کنید</p><div class="mp-contact-social-links"><a href="#" aria-label="اینستاگرام">◎</a><a href="#" aria-label="تلگرام">➤</a><a href="#" aria-label="یوتیوب">▶</a></div></article>
</section>

<section class="mp-contact-work mp-container"><div class="mp-contact-form-card" id="contact-form"><div class="mp-contact-form-head"><div class="mp-contact-kicker">فرم تماس <i></i></div><h2>پیام خود را برای ما ارسال کنید</h2><p>پرسش‌های خود را از طریق فرم زیر برای ما بگذارید. در اسرع وقت پاسخ شما را می‌دهیم.</p></div><?php if ( $sent ) : ?><div class="mp-contact-alert mp-contact-alert--success">پیام شما با موفقیت ارسال شد. ممنون که با ما در تماس هستید.</div><?php elseif ( $error ) : ?><div class="mp-contact-alert mp-contact-alert--error">ارسال پیام انجام نشد. لطفاً دوباره تلاش کنید.</div><?php endif; ?><form class="mp-contact-form" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="matin_parto_contact"><?php wp_nonce_field( 'matin_parto_contact_form', 'matin_parto_contact_nonce' ); ?><label><span>نام و نام خانوادگی <b>*</b></span><input type="text" name="contact_name" required autocomplete="name" placeholder="نام و نام خانوادگی"></label><label><span>ایمیل <b>*</b></span><input type="email" name="contact_email" required autocomplete="email" placeholder="ایمیل"></label><label class="mp-contact-form__full"><span>موضوع پیام <b>*</b></span><select name="contact_subject" required><option value="" selected disabled>انتخاب کنید</option><option>مشاوره دوره‌ها</option><option>پشتیبانی</option><option>ثبت‌نام</option><option>سایر</option></select></label><label class="mp-contact-form__full"><span>متن پیام <b>*</b></span><textarea name="contact_message" required placeholder="پیام خود را اینجا بنویسید..."></textarea></label><div class="mp-contact-form__footer"><label class="mp-contact-consent"><input type="checkbox" required><span>با ارسال پیام، با قوانین و مقررات سایت موافقت می‌کنم.</span></label><button class="mp-button mp-button--primary" type="submit">ارسال پیام <span>➤</span></button></div></form></div>
<aside class="mp-contact-aside"><div class="mp-contact-aside__media <?php echo $aside_image ? 'has-image' : ''; ?>"><?php if ( $aside_image ) : ?><img src="<?php echo esc_url( $aside_image ); ?>" alt="" loading="lazy"><?php else : ?><div class="mp-contact-image-placeholder">عکس این بخش</div><?php endif; ?><div class="mp-contact-aside__quote">« یادگیری یک زبان،<br>یک مهارت نیست،<br>یک سبک زندگی است »<small>Matin Parto</small></div></div><div class="mp-contact-aside__services"><div><span class="mp-contact-service-icon">◷</span><p><b>پاسخگویی سریع</b><small>در کمتر از ۲۴ ساعت</small></p></div><div><span class="mp-contact-service-icon">♧</span><p><b>مشاوره رایگان</b><small>برای انتخاب بهترین دوره</small></p></div><div><span class="mp-contact-service-icon">♡</span><p><b>پشتیبانی کامل</b><small>در تمام مراحل یادگیری</small></p></div></div></aside></section>

<section class="mp-contact-location mp-container"><div class="mp-contact-map <?php echo $map_image ? 'has-image' : ''; ?>"><?php if ( $map_image ) : ?><img src="<?php echo esc_url( $map_image ); ?>" alt="نقشه موقعیت متین پارتو" loading="lazy"><?php else : ?><div class="mp-contact-map-placeholder"><span>تصویر نقشه را از بخش سفارشی‌سازی انتخاب کنید</span><i></i></div><?php endif; ?></div><div class="mp-contact-location__copy"><div class="mp-contact-kicker">موقعیت ما <i></i></div><h2>آدرس و لوکیشن</h2><p>برای مراجعه حضوری، آدرس ما را در نقشه پیدا کنید.</p><strong>تهران، خیابان ولیعصر، پلاک ۱۳۲</strong><span>ساختمان متین پارتو، طبقه ۳</span><a class="mp-button mp-button--primary" href="#">مشاهده در نقشه <span>⌖</span></a></div></section>
</main>
<?php get_footer(); ?>
